[package]
name = "medallion"
version = "2.0.0"
authors = ["Thomas Gideon <cmdln@thecommandline.net>"]
description = "JWT library for rust using serde, serde_json and openssl"
homepage = "http://github.com/commandline/medallion"
repository = "http://github.com/commandline/medallion"
documentation = "https://commandline.github.io/medallion/"
readme = "README.md"
keywords = ["JWT", "token", "web"]
license = "MIT"

[dependencies]
base64 = "0.4"
openssl = "0.9"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
